// jz4740_usbioctl.h
//
// Define control codes for Jz4740_usb driver
//

#ifndef __jz4740_usbioctl__h_
#define __jz4740_usbioctl__h_

#define JZ4740_USB_IOCTL_GET_CPU_INFO		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x00, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define JZ4740_USB_IOCTL_SET_DATA_ADDRESS	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x01, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define JZ4740_USB_IOCTL_SET_DATA_LENGTH	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x02, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define JZ4740_USB_IOCTL_FLUSH_CACHES		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define JZ4740_USB_IOCTL_PROG_START1		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x04, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define JZ4740_USB_IOCTL_PROG_START2		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x05, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define JZ4740_USB_IOCTL_NOR_OPS			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x06, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define JZ4740_USB_IOCTL_NAND_OPS			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x07, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define JZ4740_USB_IOCTL_CONFIGRATION		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x09, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define JZ4740_USB_IOCTL_GET_NUM			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0a, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define JZ4740_USB_IOCTL_SDRAM_OPS			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x08, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif
