// Jz4740_usb.h
//
// Generated by DriverWizard version DriverStudio 3.1.0 (Build 1722)
// Requires Compuware's DriverWorks classes
//

#ifndef __Jz4740_usb_h__
#define __Jz4740_usb_h__

#define EOL "\n"


// Global driver trace object
extern KDebugOnlyTrace t;

class Jz4740_usb : public KDriver
{
	SAFE_DESTRUCTORS
public:
	virtual NTSTATUS DriverEntry(PUNICODE_STRING RegistryPath);
	virtual NTSTATUS AddDevice(PDEVICE_OBJECT Pdo);
	void	 LoadRegistryParameters(KRegistryKey &Params);

	int	m_Unit;
	// The following data members are loaded from the registry during DriverEntry
	ULONG m_bBreakOnEntry;

};

#endif			// __Jz4740_usb_h__
